# Site settings
title: Nic Travis Codes
header-img: img/home-bg.png
email: nptravis@gmail.com
copyright_name: nptravis
description: > # this means to ignore newlines until "baseurl:"
  My blog about coding, thanks for visiting
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nptravis
learn_profile: nptravis
email_username: nptravis@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
